-- goodrx_dbt.subscription_invoices
-- One row per invoice (billing cycle attempt). ED-filtered via subscription_category / drug.
-- Export from DataGrip → subscription_invoices.csv → upload to Databricks volume → ed_bronze.subscription_invoices

SELECT
    invoice_id,
    created_at,
    subscription_id,
    common_id,
    plan_id,
    original_payment_method_id,
    visit_id,
    prescription_id,
    invoice_number,
    card_type,
    was_paid,
    was_failed,
    is_paid,
    is_failed,
    is_refunded,
    invoice_status,
    activation_count,
    paid_at,
    failed_at,
    first_charge_at,
    refunded_at,
    num_charges,
    latest_charge_at,
    latest_term_end_at,
    latest_charge_id,
    latest_order_id,
    latest_payment_method_id,
    amount_due,
    gross_revenue,
    net_revenue,
    is_delinquent,
    caused_cancellation,
    subscription_category,
    subscription_subcategory,
    subscription_name,
    subscription_term_id,
    term_number,
    term_started_at,
    term_ended_at,
    is_trial_invoice,
    is_trial_conversion_invoice,
    subscription_plan_term_id,
    plan_term_started_at,
    plan_term_ended_at,
    drug_id,
    drug_name,
    expected_term_end_at,
    order_status,
    order_updated_at,
    cancel_requested_at,
    is_latest_term_invoice,
    is_dup,
    days_between_invoice_and_fulfillment_status,
    next_invoice_number,
    expected_refill_dt,
    next_invoice_creation_is_expected,
    next_invoice_created_at,
    next_invoice_status
FROM goodrx_dbt.subscription_invoices
WHERE subscription_subcategory = 'erectile dysfunction'
;
