-- goodrx_dbt.subscriptions
-- Core subscription records, ED-filtered (condition_id = 135 = erectile dysfunction).
-- Export from DataGrip → subscriptions.csv → upload to Databricks volume → ed_bronze.subscriptions

SELECT
    subscription_id,
    created_at,
    common_id,
    status,
    raw_subscription_type,
    condition_id,
    tenant_id,
    current_term_end,
    latest_delinquent_at,
    latest_canceled_at,
    latest_paused_at,
    latest_stripe_sub_id,
    trial_duration,
    had_trial,
    current_price,
    current_drug_id,
    current_regimen,
    current_quantity,
    current_fulfillment_method,
    current_days_supply,
    desired_refill_count,
    current_benefits_package,
    current_variant,
    activated_backend_at,
    paid_at,
    rx_written_at,
    is_paid,
    rx_is_written,
    is_activated_backend,
    is_trial_converted,
    trial_converted_at,
    trial_is_ended,
    trial_ended_at,
    is_manual_trial_canceled,
    is_failed_payment_trial_canceled,
    is_trial_canceled,
    _kafka_updated_ts,
    subscription_category,
    tenant_name,
    subscription_subcategory,
    subscription_name,
    condition_name,
    is_activated,
    activated_at,
    trial_conversion_expected_at,
    user_subscription_number,
    first_platform,
    first_session_id,
    first_grx_unique_id,
    first_channel_grouping,
    first_channel_subgrouping,
    first_traffic_source,
    first_campaign,
    user_state,
    _updated_ts
FROM goodrx_dbt.subscriptions
WHERE condition_id = 135  -- erectile dysfunction
;
